### PR TITLE
Bioinformatics recipes notebook

### PR DESCRIPTION
**Pull request by OxanaSachenkova**
This notebook will give you the recipes of the most popular data visualizations I encounter in my work as a bioinformatician. If you always wondered what bioinformatics is all about or would like to create interactive visualization for your genomic data using plot.ly, this is the place to start.

### CODE REVIEW

**Comment by etpinard** [comment]
This NB is fantastic. Thank you very much.

If this repo were better designed, this PR would be ready to be merged. My apologies.

Unfortunately, looks like you forked this repo before the `aricraft_pitch` NB got merged making the config file [off your branch](https://github.com/OxanaSachenkova/IPython-plotly/blob/master/notebooks/references.json) incompatible with the [master version](https://github.com/plotly/IPython-plotly/blob/master/notebooks/references.json). 

Can I ask you to merge master and run `make run-publish nb=bioinformatics`?

Thanks again.

**Comment by OxanaSachenkova** [comment]
@etpinard Sorry about that. 
Should be ready to merge now!

**Comment by etpinard** [comment]
Beautiful. Thank you so much.

**Comment by etpinard** [comment]
https://plot.ly/ipython-notebooks/bioinformatics/

**Pull request merged**
