### PR TITLE
color lover notebook

### PR DESCRIPTION
**Pull request by NicoleGrondin**
@mkcor I hope this is ok...

### CODE REVIEW

**Comment by mkcor** [comment]
@NicoleGrondin Can you please rerun all cells in the notebook, so that code cells are numbered from 1 to N?

**Comment by mkcor** [comment]
Please punctuate or break lines in `Install with pip, sudo pip install colorlover Code and documentation on Github`.

**Comment by mkcor** [comment]
Spacing is off in `HTML(cl.to_html( cl.scales['11'] )) # All scales with 11 colors`.

**Comment by mkcor** [comment]
No spaces inside `( )` (many code cells).

**Comment by mkcor** [comment]
(You can always refer to [pep8](https://www.python.org/dev/peps/pep-0008/) if unsure.)

**Comment by mkcor** [comment]
Period missing in last sentence.

**Comment by mkcor** [comment]
For the sake of authority, I think it would be nice to share a reference, such as http://matplotlib.org/users/colormaps.html.

**Comment by chriddyp** [comment]
this repo and contents has moved to https://github.com/plotly/documentation/blob/source/Contributing.md, please update there!

**Pull request closed without merging**
