### PR TITLE
Added Apache Spark

### PR DESCRIPTION
**Pull request by anabranch**
Unfortunately I got more errors at Step 3 - I couldn't compile the notebook into the required form.

### CODE REVIEW

**Comment by anabranch** [comment]
[NbConvertApp] Using existing profile dir: u'/Users/bill_chambers/.ipython/profile_default'
[NbConvertApp] WARNING | pattern u'apachespark.tmp.ipynb' matched no files
This application is used to convert notebook files (*.ipynb) to various other
formats.

WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
--init
    Initialize profile with default config files.  This is equivalent
    to running `ipython profile create <profile>` prior to startup.
--quiet
    set log level to logging.CRITICAL (minimize logging output)
--stdout
    Write notebook output to stdout instead of files.
--profile=<Unicode> (BaseIPythonApplication.profile)
    Default: u'default'
    The IPython profile to use.
--reveal-prefix=<Unicode> (RevealHelpPreprocessor.url_prefix)
    Default: 'reveal.js'
    The URL prefix for reveal.js. This can be a a relative URL for a local copy
    of reveal.js, or point to a CDN.
    For speaker notes to work, a local reveal.js prefix must be used.
--ipython-dir=<Unicode> (BaseIPythonApplication.ipython_dir)
    Default: u''
    The name of the IPython directory. This directory is used for logging
    configuration (through profiles), history storage, etc. The default is
    usually $HOME/.ipython. This options can also be specified through the
    environment variable IPYTHONDIR.
--writer=<DottedObjectName> (NbConvertApp.writer_class)
    Default: 'FilesWriter'
    Writer class used to write the  results of the conversion
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--to=<CaselessStrEnum> (NbConvertApp.export_format)
    Default: 'html'
    Choices: ['custom', 'html', 'latex', 'markdown', 'python', 'rst', 'slides']
    The export format to be used.
--template=<Unicode> (TemplateExporter.template_file)
    Default: u'default'
    Name of the template file to use
--output=<Unicode> (NbConvertApp.output_base)
    Default: ''
    overwrite base name use for output files. can only  be use when converting
    one notebook at a time.
--post=<DottedOrNone> (NbConvertApp.postprocessor_class)
    Default: u''
    PostProcessor class used to write the  results of the conversion
--config=<Unicode> (BaseIPythonApplication.extra_config_file)
    Default: u''
    Path to an extra config file to load.
    If specified, load this config file in addition to any other IPython config.
--profile-dir=<Unicode> (ProfileDir.location)
    Default: u''
    Set the profile location directly. This overrides the logic used by the
    `profile` option.

To see all available configurables, use `--help-all`

Examples
--------

    The simplest way to use nbconvert is

    > ipython nbconvert mynotebook.ipynb

    which will convert mynotebook.ipynb to the default format (probably HTML).

    You can specify the export format with `--to`.
    Options include ['custom', 'html', 'latex', 'markdown', 'python', 'rst', 'slides']

    > ipython nbconvert --to latex mynotebook.ipynb

    Both HTML and LaTeX support multiple output templates. LaTeX includes
    'base', 'article' and 'report'.  HTML includes 'basic' and 'full'. You
    can specify the flavor of the format used.

    > ipython nbconvert --to html --template basic mynotebook.ipynb

    You can also pipe the output to stdout, rather than a file

    > ipython nbconvert mynotebook.ipynb --stdout

    A post-processor can be used to compile a PDF

    > ipython nbconvert mynotebook.ipynb --to latex --post PDF

    You can get (and serve) a Reveal.js-powered slideshow

    > ipython nbconvert myslides.ipynb --to slides --post serve

    Multiple notebooks can be given at the command line in a couple of
    different ways:
  1 Added Apache Spark

    > ipython nbconvert notebook*.ipynb
    > ipython nbconvert notebook1.ipynb notebook2.ipynb

    or you can specify the notebooks list in a config file, containing::

        c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

    > ipython nbconvert --config mycfg.py

make: *** [run] Error 255

**Comment by etpinard** [comment]
Hi @anabranch 

Looks like you forgot to specify which notebook to run.

In your case, try running `make run nb=apachespark`

**Comment by anabranch** [comment]
That's what I've been running @etpinard however it seems to be looking for a apachespark.tmp not the actual notebook file that is just apachespark.ipynb. 

```
[NbConvertApp] WARNING | pattern u'apachespark.tmp.ipynb' matched no files
    This application is used to convert notebook files (*.ipynb) to various other
    formats.
```


    make run nb=apachespark
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    ---------------------------------------------------------------------------
    Exception                                 Traceback (most recent call last)
    ~/Dev/IPython-plotly/_makescripts/trim.py in <module>()
         35
         36 if __name__ == "__main__":
    ---> 37     main()

    ~/Dev/IPython-plotly/_makescripts/trim.py in main()
         15 def main():
         16
    ---> 17     path_handler = common.PathHandler('trim')
         18
         19     for arg in path_handler.args:

    ~/Dev/IPython-plotly/_makescripts/common.pyc in __init__(self, name)
         13         self.GLOBALS = self._get_globals()
         14         self.nbs = self.load_references()['notebooks']
    ---> 15         self.args = self._get_args()
         16
         17     def _get_globals(self):

    ~/Dev/IPython-plotly/_makescripts/common.pyc in _get_args(self)
         41                 'Invalid notebook directory.\n\n'
         42                 'The available notebook directories are:\n'
    ---> 43                 '  {}'.format('\n  '.join(self.nbs))
         44             )
         45         else:

    Exception: Invalid notebook directory.

    The available notebook directories are:
      ukelectionbbg
      salesforce
      gmail
      markowitz
      cartodb
      networkx
      make_subplots
      basemap
      collaborate
    [NbConvertApp] Using existing profile dir: u'/Users/bill_chambers/.ipython/profile_default'
    [NbConvertApp] WARNING | pattern u'apachespark.tmp.ipynb' matched no files
    This application is used to convert notebook files (*.ipynb) to various other
    formats.

**Comment by etpinard** [comment]
Oh right.

You first need to add `"apachespark"` to [notebooks/references.json](https://github.com/plotly/IPython-plotly/blob/master/notebooks/references.json#L2).

`"apachespark"` should be placed in `notebooks[0]` to correspond to the first item listed on https://plot.ly/ipython-notebooks/ :

image

More info [here](https://github.com/plotly/IPython-plotly/blob/master/CONTRIBUTING.md#references-file). But, I just the realized that the contributing instructions for this part are a little confusing. I'll update them soon.

Sorry for the inconvenience

**Pull request closed without merging**
