### PR TITLE
Added Amazon Redshift Notebook

### PR DESCRIPTION
**Pull request by anabranch**

### CODE REVIEW

**Comment by etpinard** [comment]
@anabranch 

Hi, thanks again for the awesome content.

I have a few recommendations:

- [ ] the y-axis of the `redshift/state and music taste` heatmap doesn't show all the states / provinces - which is misleading for this categorical heatmap. Something like [this](https://plot.ly/~etpinard/3259) would give a better picture of the dataset. (To generate the graph, I simply added a custom height and set `yaxis.autotick: false` + `yaxis.dtick: 1`). Additionally -- if not too difficult for you -- could you sort the y-axis categories (e.g. by alphabetical order or row-wise total)?

- [ ] add a title to `redshift/state and music taste` heatmap

- [ ] use `tls.make_subplots` instead of `tls.get_subplots` here 

image


Apart from that, your NB looks amazing.

**Comment by anabranch** [comment]
I set an arbitrary height but I'm not sure it registered because it didn't seem to in my notebook. What height did you set it to @etpinard ?

**Comment by etpinard** [comment]
@anabranch You forgot to package layout and data together before calling `py.iplot` 

image

**Comment by etpinard** [comment]
@anabranch For the best results inside the NB, you'll also need to specify the iframe's height.

You can do so using the `height` kwarg in `py.iplot` as displayed [here](https://plot.ly/python/histograms-and-box-plots-tutorial/#in-[29])

image

**Comment by anabranch** [comment]
Think I got it...finally @etpinard thanks for the help.

**Comment by etpinard** [comment]
Beautiful. Great job!

**Comment by etpinard** [comment]
@anabranch https://plot.ly/ipython-notebooks/amazon-redshift/

**Pull request merged**
