### PR TITLE
6 new Notebooks

### PR DESCRIPTION
**Pull request by NicoleGrondin**
Panda data frame plotting, working with colors, updating plots with cron jobs, generating html reports,
connecting to my SQL & reading from Socrata.

@etpinard

### CODE REVIEW

**Comment by etpinard** [comment]
Nice.

Looks like every NB got covered with no issues.

The sample notebook section on [/ipython-notebook](https://plot.ly/ipython-notebooks/) is getting a little crowded, so we'll wait for the new `gh-pages` framework to roll in before merging.

**Comment by NicoleGrondin** [comment]
Sounds good! Thanks :)

**Comment by NicoleGrondin** [comment]
@etpinard the new notebook template is up at https://plot.ly/python/ipython-notebooks/
ok to merge?

**Comment by etpinard** [comment]
Wow. Looking great!

Everything looks good except that the [references.json](https://github.com/plotly/IPython-plotly/pull/55/files#diff-7b9ccea0f9595cc19ad5d0360e1737a8) file on your branch is missing a few entries in comparison with the [master version](https://github.com/plotly/IPython-plotly/blob/master/notebooks/references.json).

You'll need to merge the latest master in your `Pandas-color-and-Socrata` branch and then run `make run-publish` for all the NBs you added (sorry for the inconvenience).

**Comment by mkcor** [comment]
Could one PR be *at most* one notebook, please? I think that would be a much better process: it would immensely ease the review process and make history a lot more readable (there's 1 commit here...?!?), both going hand in hand...
@etpinard @NicoleGrondin 
I say :-1: here and would like to ask for a separate submission.

**Comment by chriddyp** [comment]
this repo and contents has moved to https://github.com/plotly/documentation/blob/source/Contributing.md, please update there!

**Pull request closed without merging**
