### PR TITLE
Pytables

### PR DESCRIPTION
**Pull request by chriddyp**
Pre-publication by @anabranch , up for review and edits. I'm in the process of making several changes

### CODE REVIEW

**Comment by etpinard** [comment]
Remarks:

- [ ] get rid of the SSL warnings - info [here](https://github.com/plotly/python-user-guide/issues/15#issuecomment-100037103)
- [ ] add units to each graph
- [ ] note that [custom CSS](https://github.com/plotly/IPython-plotly/commit/add7111b80b11fdc3126a97783109e1ce63e16d7) is stripped in the published process at the moment.

**Comment by anabranch** [comment]
I can't make changes on this branch, should I do it on the original notebook and then create a PR?

**Comment by chriddyp** [comment]
woops. @anabranch I'll add you to this repo

**Comment by chriddyp** [comment]
@anabranch - just added you!

**Comment by anabranch** [comment]
quashed errors, added units

**Comment by anabranch** [comment]
@etpinard any update on this?

**Comment by etpinard** [comment]
@anabranch Sorry about the delay. This is looking great :+1:

**Pull request merged**
