### PR TITLE
Bicycle control notebook

### PR DESCRIPTION
**Pull request by moorepants**
This is the draft for a notebook on balancing and controlling a bicycle with a sequential dual-loop controller using the python-control package. The main things I want to get across are:
- Designing heading controller using the python-control tools
- Demonstration of counter steering and what it means

I'd like to have two to three types of plots:
- Root Locus
- Time response
- Bode Diagram (not in there yet)

This has most of the text, all essential graphs, and most all info I was hoping to present but it isn't quite polished. I'm not completely happy with the controller design and would like to get it tuned a little better (get the control working took me a bit longer than expected).

Some things to to or not to do:
- [x] Do a better job on the controller design so that the heading control is much more responsive.
- [x] Add in the last graph showing the steer angle required for a commanded heading and explain counter steering in a paragraph.
- [ ] Some how add the damping ratio and natural frequency in the hover label like I did the gain. Not sure how to do this with Plotly. This would make the root locus plot somewhat equivalent with what Matlab offers.
- [ ] Make an interactive PID tuner widget. Probably wouldn't be too hard and you could fiddle with the PID gains to see the change in the step response.
- [ ] Can the installation be based on conda? BTW, it'd be nice to have a plotly conda package (ideally included with Anaconda). Maybe you all should call up Continuum and try to get it in. I'm cohorts with a lead dev on conda if you want to make that happen.
- [x] Flesh out the writing in the later part of the notebook.
- [x] Grammar and spell check.

If you'd like to provide any feedback now before I take this too far, that'd be helpful. I've, of course, spent more time than expected (~12 hrs so far). I'd particularly like to know what scope you'd like this to be. Let me know what you all think.

### CODE REVIEW

**Comment by etpinard** [comment]
This NB is looking great. It is definitely one of the best in this repo. Thank you very much for your efforts.

> Some how add the damping ratio and natural frequency in the hover label like I did the gain. Not sure how to do this with Plotly. This would make the root locus plot somewhat equivalent with what Matlab offers.

Something like [this example](https://plot.ly/python/bubble-charts-tutorial/#in-[14]) could be similar to your needs.

>  Can the installation be based on conda? BTW, it'd be nice to have a plotly conda package (ideally included with Anaconda). Maybe you all should call up Continuum and try to get it in. I'm cohorts with a lead dev on conda if you want to make that happen.

Not yet I think (cc @msund).

Don't hesitate to ask me any other questions.

**Comment by msund** [comment]
@moorepants, we aren't part of Anaconda, though that's a cool idea. I'd appreciate an intro if you're open to it. I'm at matt@plot.ly.

**Comment by moorepants** [comment]
@etpinard Thanks for the tip. I'll have a look at the example.

@msund At the bare minimum you all can self host the plotly interfaces on binstar. For example, if the plotly python source is pure python this is a 10 minute process. Once you do that you can have people install using conda like so:

```
conda install -c plotly plotly
```

If you'd like plotly to be included in the Anaconda distribution (so that everyone that downloads anaconda will have access to plotly), then all people have to type is:

```
conda install plotly
````

The conda package manager is language agnostic, so you can have it install your R and Python interfaces, for example.

If you want me to give you more details I can.

**Comment by msund** [comment]
@moorepants, definitely a route worth mentioning. I think our ideal would be to be in their distributed packages. We have that with Enthought's Canopy. If you'd be open to make an intro, that'd be much appreciate.

**Comment by moorepants** [comment]
Ok, I'll contact my friend at continuum.

**Comment by moorepants** [comment]
Ok this is in a final draft form. Please review the content and let me know if you are happy with it.

I have some ideas for interactive plots using widgets and even just adding more information to the root locus text hovers (as noted above), but haven't spent time on doing that. So if you want something fancier with the Plotly graphs, let me know and I can spend more time figuring those things out.

And finally let me know what else needs to be done to have this "work" with your build system. I haven't looked into that at all.

**Comment by etpinard** [comment]
Your notebook is world class.

- I was able to make it work on my machine.
- I wouldn't bother adding widgets as embedding widget interactivity on a web page is not trivial.

Can you filled a [config file](https://github.com/plotly/IPython-plotly/blob/master/_makescripts/data/config-init.json), add `bicycle_control` to the top of the [references file](https://github.com/plotly/IPython-plotly/blob/master/notebooks/references.json) and follow the publish [steps](https://github.com/plotly/IPython-plotly/blob/master/CONTRIBUTING.md#step-1-install-requirements) ?

**Comment by moorepants** [comment]
I created the config file and edited the references file, but the make targets fail because I've already created my notebook directory. Do I need to do that stuff?

Also, can someone please proofread the text in the notebook for me? I'm notorious for spelling mistakes (not to mention grammar) and IPython doesn't have any kind of spell check.

**Comment by moorepants** [comment]
Also note that this is a v4 notebook. I just saw #29.

**Comment by moorepants** [comment]
I posted a couple of the build issues. Seem like the `trim.py` file is failing. I'm not sure what that is all about so I'll leave it to you.

**Comment by etpinard** [comment]
Your `config.json` contains comments, making `json.load` fail and hence `trim.py` fail.

https://github.com/plotly/IPython-plotly/blob/master/CONTRIBUTING.md#step-2

**Comment by etpinard** [comment]
Looking good! I'll get someone to proofread your NB tomorrow.

in the meantime can you merge master into your branch and run `make publish` again?

The [`references.json`](https://github.com/plotly/IPython-plotly/blob/master/notebooks/references.json) is poorly designed. Conflicts occur every time someone merges in a note while someone else is working on a branch.

**Comment by moorepants** [comment]
Conflicts fixed. I can ask around for a proofread too.

**Comment by moorepants** [comment]
Ok, I had someone proofread the notebook for me. This is fine from my end and should be ready to be merged.

**Comment by etpinard** [comment]
great job.

**Pull request merged**
