### PR TITLE
pca 1st commit

### PR DESCRIPTION
**Pull request by rasbt**
Hi,

I have some troubles with `make publish`, I was wondering if this is somehow related to the the IPython Notebook 3 overhaul?

The error I get is 
<pre>(py2)sebastian ~/github/IPython-plotly> make run nb=principal_component_analysis
[NbConvertApp] Converting notebook principal_component_analysis.tmp.ipynb to html
[NbConvertApp] Writing 273763 bytes to principal_component_analysis.tmp.html
[NbConvertApp] Converting notebook principal_component_analysis.tmp.ipynb to python
[NbConvertApp] Writing 19571 bytes to principal_component_analysis.tmp.py
(py2)sebastian ~/github/IPython-plotly> make publish nb=principal_component_analysis
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/sebastian/github/IPython-plotly/_makescripts/publish.py in <module>()
    201 
    202 if __name__ == "__main__":
--> 203     main()

/Users/sebastian/github/IPython-plotly/_makescripts/publish.py in main()
    175         # Update body
    176         remove_title(body)
--> 177         update_anchors(body)
    178         add_lightbox(body)
    179         add_in_out_anchors(body)

/Users/sebastian/github/IPython-plotly/_makescripts/publish.py in update_anchors(body)
     65 
     66     for anchor in anchors:
---> 67         if anchor['href'].startswith((user_root, '#')):
     68             continue
     69         elif anchor['href'].startswith(site_root):

/Users/sebastian/anaconda/envs/py2/lib/python2.7/site-packages/bs4/element.pyc in __getitem__(self, key)
    903         """tag[key] returns the value of the 'key' attribute for the tag,
    904         and throws an exception if it's not there."""
--> 905         return self.attrs[key]
    906 
    907     def __iter__(self):

KeyError: 'href'
> /Users/sebastian/anaconda/envs/py2/lib/python2.7/site-packages/bs4/element.py(905)__getitem__()
    904         and throws an exception if it's not there."""
--> 905         return self.attrs[key]
    906 

ipdb> ^C
</pre>

Another question: The current setup only supports Python 2.7? I had problems using Python 3 initially:

<pre>(py3)sebastian ~/github/IPython-plotly> make publish nb=principal_component_analysis
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/sebastian/github/IPython-plotly/_makescripts/publish.py in <module>()
      5 import warnings
      6 
----> 7 import delightfulsoup as ds
      8 import djangofy as dfy
      9 

/Users/sebastian/anaconda/envs/py3/lib/python3.4/site-packages/delightfulsoup/__init__.py in <module>()
      6 """
      7 
----> 8 from io import (
      9     load_soup,
     10     dump_soup,

ImportError: cannot import name 'load_soup'
> /Users/sebastian/anaconda/envs/py3/lib/python3.4/site-packages/delightfulsoup/__init__.py(8)<module>()
      7 
----> 8 from io import (
      9     load_soup,

ipdb> ^C</pre>

Hope you have an idea about what's going on here.

Best,
Sebastian

### CODE REVIEW

**Comment by etpinard** [comment]
Hi,

First off, thank you very much for doing this. Your NB looks awesome.

Regarding the error in `make publish`: looks like your NB contains 2 cells with `<a name=></a>`

image

which causes the publish script to freak out (it expects an `href` attribute).

Is there a reason for having those anchors in there? If not, I'll modify the publish script so that anchors of the sort are purged upon publishing.

Regarding python 3 support, the short answer is no. Thanks for noticing, I'll add a note about it in the Contributing.md file.

**Comment by rasbt** [comment]
Sorry for the inconvenience, @etpinard, I didn't know that those "<a name=></a>" tags were (still) in there -- there is really no reason to keep. But now I am facing another problem

    (py27)~/github/IPython-plotly >make publish nb='principal_component_analysis'
    /Users/sebastian/github/IPython-plotly/_makescripts/publish.py:43: UserWarning: No H1 found
      warnings.warn("No H1 found")

Could this be due to the IPython notebook 3.0 overhaul? E.g., the h1 headline would look like this:

<pre> {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Principal Component Analysis in 3 Simple Steps"
   ]
  }, </pre>

**Comment by etpinard** [comment]
Oh. That `h1` warning is an artifact, you can ignore it.

Looks the like the publish step didn't go through correctly though: only two cells appear in the published [html file](https://github.com/rasbt/IPython-plotly/blob/master/_published/includes/principal_component_analysis/body.html).

I pulled down your branch and ran `make publish` and everything looks good on my machine.

Can I ask you to run `pip freeze` and send me the output?

Thank you in advance.

**Comment by rasbt** [comment]
The pip freeze output would be

<pre>
apptools==4.2.1
argcomplete==0.6.7
astropy==0.3
atom==0.3.7
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.3.2
binstar==0.4.4
biopython==1.63
bitarray==0.8.1
blaze==0.4.2
blz==0.6.1
bokeh==0.4.1
boto==2.25.0
casuarius==1.1
cdecimal==2.3
chaco==4.4.1
colorama==0.2.7
configobj==4.7.2
cssselect==0.9.1
cubes==0.10.2
Cython==0.20.1
DataShape==0.1.1
delightfulsoup==0.0.9
djangofy==0.0.14
docutils==0.11
dsltools==0.2.6
enable==4.3.0
enaml==0.9.1
envisage==4.4.0
Flask==0.10.1
Flask-Shelve==0.1.1
Flask-WTF==0.10.3
future==0.11.2
gevent==1.0
gevent-websocket==0.9.2
gevent-zeromq==0.2.2
google==1.5
google-api-python-client==1.3.1
greenlet==0.4.2
grin==1.2.1
h5py==2.2.1
html5lib==0.999
httplib2==0.9
ipython==3.1.0
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.4.0
keyring==3.3
Kivy==1.8.0
Kivy-Garden==0.1.1
kiwisolver==0.1.2
llvmpy==0.12.3
lxml==3.3.1
MarkupSafe==0.23
matplotlib==1.4.2
mayavi==4.3.1
MDP==3.3
mistune==0.5.1
mock==1.0.1
netCDF4==1.0.8
networkx==1.8.1
nltk==3.0.0
nose==1.3.0
numba==0.12.1
numexpr==2.3.1
numpy==1.8.2
oauth2client==1.4.2
openpyxl==1.8.2
pandas==0.15.1
parakeet==0.23.2
patsy==0.2.1
pep8==1.4.6
PIL==1.1.7
plotly==1.6.15
ply==3.4
prettytable==0.7.2
psutil==1.2.1
py==1.4.20
pyasn1==0.1.7
pyasn1-modules==0.0.5
PyAudio==0.2.7
pycosat==0.6.0
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.0
pyface==4.4.0
pyflakes==0.7.3
Pygments==1.6
pykit==0.2.0
pyparsing==2.0.1
PySAL==1.6.0
pysam==0.6
pytest==2.5.2
python-dateutil==1.5
pytz==2014.9
PyYAML==3.11
pyzmq==14.5.0
redis==2.9.1
requests==2.5.0
rope==0.9.4
rsa==3.1.4
scikit-image==0.9.3
scikit-learn==0.14.1
scipy==0.13.3
seaborn==0.5.0
simplejson==3.6.5
six==1.8.0
Sphinx==1.2.1
spyder==2.2.5
SQLAlchemy==0.9.2
statsmodels==0.5.0
sympy==0.7.4.1
tables==3.1.0
tornado==4.1
traits==4.4.0
traitsui==4.4.0
ujson==1.33
Unidecode==0.4.16
uniqueprot==2.0.4
uritemplate==0.6
VTK==5.10.1
Werkzeug==0.9.6
wordcloud==1.0.0
WTForms==2.0.1
xlrd==0.9.2
XlsxWriter==0.5.2
xlwt==0.7.5
</pre>

**Comment by etpinard** [comment]
@rasbt I can't replicate the bug on my machine. One of my colleague has had the same problem, so I'll try to investigate the problem on his computer. 

In the meantime, I'll merge in your NB with the full output in PR #26.

**Comment by etpinard** [comment]
https://plot.ly/ipython-notebooks/principal-component-analysis/

**Comment by etpinard** [comment]
Thanks again!

**Comment by rasbt** [comment]
Just took a look at the ipynb, and I have to say that I really like the CSS! Thanks!

**Pull request closed without merging**
