### PR TITLE
Added a note about the author on the bicycle control notebook.

### PR DESCRIPTION
**Pull request by moorepants**
I just wanted to add my name to the bicycle control notebook.

I'm getting an error on building though:

```
(plotly-notebooks)moorepants@moorepants-2170p:IPython-plotly(name)$ make run nb=bicycle_control
[NbConvertApp] Converting notebook bicycle_control.tmp.ipynb to html
[NbConvertApp] Writing 271996 bytes to bicycle_control.tmp.html
[NbConvertApp] Converting notebook bicycle_control.tmp.ipynb to python
[NbConvertApp] Writing 21532 bytes to bicycle_control.tmp.py
(plotly-notebooks)moorepants@moorepants-2170p:IPython-plotly(name)$ make publish nb=bicycle_control
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in <module>()
    211 
    212 if __name__ == "__main__":
--> 213     main()

/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in main()
    181         # Download images
    182         wget_images(body, arg, config['title_short'],
--> 183                     dir_nb, path_image, tree['static']['image'])
    184 
    185         # Update body

/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in wget_images(body, nb, name, dir_nb, img_folder_on_streambed, img_folder_in_repo)
     34                          translate_src=True,
     35                          custom_img_name=custom_img_name,
---> 36                          img_alt=img_alt)
     37 
     38 

TypeError: wget_images() got an unexpected keyword argument 'dir_root'
```

### CODE REVIEW

**Comment by etpinard** [comment]
you'll need to reinstall the requirements

**Comment by moorepants** [comment]
I updated an now I get this:

```
(plotly-notebooks)moorepants@moorepants-2170p:IPython-plotly(name)$ make publish nb=bicycle_control
/home/moorepants/Jobs/plotly/IPython-plotly
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in <module>()
    211 
    212 if __name__ == "__main__":
--> 213     main()

/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in main()
    198     # Append and dump references
    199     references = path_handler.load_references()
--> 200     references = append_references(references, path_handler)
    201     ds.dump_json(references, tree['includes']['references'])
    202 

/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/publish.py in append_references(references, path_handler)
    150         )
    151 
--> 152         config = path_handler.load_config(nb)
    153         references['splash'] += [dict(
    154             title=config['title'],

/home/moorepants/Jobs/plotly/IPython-plotly/_makescripts/common.pyc in load_config(self, arg)
     56     def load_config(self, arg):
     57         path_config = os.path.join(self.get_path(arg), 'config.json')
---> 58         return ds.load_json(path_config)
     59 
     60     def load_references(self):

/home/moorepants/anaconda/envs/plotly-notebooks/lib/python2.7/site-packages/delightfulsoup/io.pyc in load_json(path_json)
     44     """
     45 
---> 46     with open(path_json, 'r') as f:
     47         return _json.load(f)
     48 

IOError: [Errno 2] No such file or directory: u'notebooks/pytables/config.json'
```

**Comment by moorepants** [comment]
That's because of case sensitivity I suppose.

**Comment by etpinard** [comment]
@moorepants just to let you know, this repo will become obsolete in the next few days.

We are moving the plotly IPython notebooks to a new repo (where all the plotly docs reside). 

Very soon, you'll be able to publish (or edit) your NBs by adding a [single cell](https://github.com/plotly/documentation/pull/165) to your NB. 

Look for an official announcement within the next few days.

**Comment by chriddyp** [comment]
this repo and contents has moved to https://github.com/plotly/documentation/blob/source/Contributing.md, please update there!

**Comment by chriddyp** [comment]
in particular, this control notebook is here: https://github.com/plotly/documentation/blob/source/_posts/tutorials/bicycle_control.ipynb

**Comment by moorepants** [comment]
I don't really have time to learn a new build system. Can one of you just add this paragraph to the bottom of my notebook?

**Pull request closed without merging**
